// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	Domain "task_manager_ca/Domain"

	mock "github.com/stretchr/testify/mock"
)

// JwtService is an autogenerated mock type for the JwtService type
type JwtService struct {
	mock.Mock
}

// CreateJwtToken provides a mock function with given fields: _a0
func (_m *JwtService) CreateJwtToken(_a0 Domain.User) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateJwtToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(Domain.User) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(Domain.User) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(Domain.User) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJwtService creates a new instance of JwtService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJwtService(t interface {
	mock.TestingT
	Cleanup(func())
}) *JwtService {
	mock := &JwtService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
