// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	Domain "task_manager_ca/Domain"

	mock "github.com/stretchr/testify/mock"
)

// UserUseCaseI is an autogenerated mock type for the UserUseCaseI type
type UserUseCaseI struct {
	mock.Mock
}

// Login provides a mock function with given fields: user
func (_m *UserUseCaseI) Login(user Domain.User) (string, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(Domain.User) (string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(Domain.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(Domain.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: user
func (_m *UserUseCaseI) Register(user Domain.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(Domain.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserUseCaseI creates a new instance of UserUseCaseI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserUseCaseI(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserUseCaseI {
	mock := &UserUseCaseI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
